power <- read.table("household_power_consumption.txt", header=T, sep=";", colClasses = "character")
power$DateTime <- paste(power$Date, power$Time)
power$Date <- as.Date(power$Date, "%d/%m/%Y") 
power <- power[!is.na(power$Date) & power$Date == "2007-02-01" | power$Date == "2007-02-02",]
power$Global_active_power <- as.numeric(power$Global_active_power)
power$Sub_metering_1 <- as.numeric(power$Sub_metering_1)
power$Sub_metering_2 <- as.numeric(power$Sub_metering_2)
power$Sub_metering_3 <- as.numeric(power$Sub_metering_3)
power$DateTime <- strptime(power$DateTime, "%d/%m/%Y %H:%M:%S") 
plot(power$DateTime, power$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(power$DateTime, power$Sub_metering_2, col="red")
lines(power$DateTime, power$Sub_metering_3, col="blue")
legend("topright", col = c("black", "red", "blue"), cex = 0.95, lty=1, legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png")
dev.off()